---
- hosts: hosts
  remote_user: cesar

  tasks:
    - name: Mostrar hostname del nodo
      shell: /usr/bin/cat /etc/hostname

    - name: Cambiar hostname nodo
      shell: sudo /usr/bin/hostnamectl set-hostname "prueba02.localhost"

    - name: Mostrar cambio de hostname
      shell: /usr/bin/cat /etc/hostname
