---
-
  hosts: hosts
  remote_user: cesar

  tasks:
    -
      name: Mostrar hostname del nodo
      shell: /usr/bin/cat /etc/hostname
    -
      name: Mostrar cambio de hostname
      command: ['cat','/etc/hostname']
