---
- hosts: hosts
  remote_user: cesar
  
  tasks:
  - name: Mostrar hostname del nodo
    command: whoami
    register: name
  - debug: msg={{ name.stdout }}
  
  - name: Mostrar cambio de hostname
    become: true
    command: whoami
    register: name
  - debug: msg={{ name.stdout }}
